<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="18846" started-at="2021-06-09T14:37:08 IST" finished-at="2021-06-09T14:37:27 IST">
    <groups>
    </groups>
    <test name="USER LOGIN" duration-ms="10677" started-at="2021-06-09T14:37:08 IST" finished-at="2021-06-09T14:37:19 IST">
      <class name="com.Docker.Selenium_Docker.LoginTest">
        <test-method status="PASS" signature="beforeTest(java.lang.String, org.testng.ITestContext)[pri:0, instance:com.Docker.Selenium_Docker.LoginTest@e874448]" name="beforeTest" is-config="true" duration-ms="3219" started-at="2021-06-09T14:37:08 IST" finished-at="2021-06-09T14:37:11 IST">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@30f4b1a6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.Docker.Selenium_Docker.LoginTest@e874448]" name="beforeClass" is-config="true" duration-ms="48" started-at="2021-06-09T14:37:11 IST" finished-at="2021-06-09T14:37:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="Login_Test(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Docker.Selenium_Docker.LoginTest@e874448]" name="Login_Test" duration-ms="6602" started-at="2021-06-09T14:37:11 IST" finished-at="2021-06-09T14:37:18 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Inpatient Ward]]>
              </value>
            </param>
            <param index="1">
              <value is-null="true"/>
            </param>
            <param index="2">
              <value is-null="true"/>
            </param>
            <param index="3">
              <value>
                <![CDATA[TRUE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_Test -->
        <test-method status="FAIL" signature="afterTest()[pri:0, instance:com.Docker.Selenium_Docker.LoginTest@e874448]" name="afterTest" is-config="true" duration-ms="764" started-at="2021-06-09T14:37:18 IST" finished-at="2021-06-09T14:37:19 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Test Name Failed : USER LOGIN
Failed while Validating  : Failing of Assertion
Class Failed : com.Docker.Selenium_Docker.LoginTest
 METHOD FAILED  : Login_Test
 IN Line number : 37
Assertion Fail in URL : https://demo.openmrs.org/openmrs/referenceapplication/home.page
 Failure Message  : Why are you failing expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Test Name Failed : USER LOGIN
Failed while Validating  : Failing of Assertion
Class Failed : com.Docker.Selenium_Docker.LoginTest
 METHOD FAILED  : Login_Test
 IN Line number : 37
Assertion Fail in URL : https://demo.openmrs.org/openmrs/referenceapplication/home.page
 Failure Message  : Why are you failing expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at resource.BaseTest.afterTest(BaseTest.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.afterRun(TestRunner.java:847)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.Docker.Selenium_Docker.LoginTest -->
    </test> <!-- USER LOGIN -->
    <test name="USER LOGIN Invalid User" duration-ms="8150" started-at="2021-06-09T14:37:19 IST" finished-at="2021-06-09T14:37:27 IST">
      <class name="com.Docker.Selenium_Docker.LoginTest">
        <test-method status="PASS" signature="beforeTest(java.lang.String, org.testng.ITestContext)[pri:0, instance:com.Docker.Selenium_Docker.LoginTest@1b26f7b2]" name="beforeTest" is-config="true" duration-ms="1528" started-at="2021-06-09T14:37:19 IST" finished-at="2021-06-09T14:37:20 IST">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@405325cf]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.Docker.Selenium_Docker.LoginTest@1b26f7b2]" name="beforeClass" is-config="true" duration-ms="0" started-at="2021-06-09T14:37:20 IST" finished-at="2021-06-09T14:37:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="Login_Test(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Docker.Selenium_Docker.LoginTest@1b26f7b2]" name="Login_Test" duration-ms="5921" started-at="2021-06-09T14:37:20 IST" finished-at="2021-06-09T14:37:26 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Inpatient Ward]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Adminstrator]]>
              </value>
            </param>
            <param index="2">
              <value is-null="true"/>
            </param>
            <param index="3">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_Test -->
        <test-method status="FAIL" signature="afterTest()[pri:0, instance:com.Docker.Selenium_Docker.LoginTest@1b26f7b2]" name="afterTest" is-config="true" duration-ms="692" started-at="2021-06-09T14:37:26 IST" finished-at="2021-06-09T14:37:27 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Test Name Failed : USER LOGIN Invalid User
Failed while Validating  : Failing of Assertion
Class Failed : com.Docker.Selenium_Docker.LoginTest
 METHOD FAILED  : Login_Test
 IN Line number : 37
Assertion Fail in URL : https://demo.openmrs.org/openmrs/referenceapplication/login.page
 Failure Message  : Why are you failing expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Test Name Failed : USER LOGIN Invalid User
Failed while Validating  : Failing of Assertion
Class Failed : com.Docker.Selenium_Docker.LoginTest
 METHOD FAILED  : Login_Test
 IN Line number : 37
Assertion Fail in URL : https://demo.openmrs.org/openmrs/referenceapplication/login.page
 Failure Message  : Why are you failing expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at resource.BaseTest.afterTest(BaseTest.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.afterRun(TestRunner.java:847)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.Docker.Selenium_Docker.LoginTest -->
    </test> <!-- USER LOGIN Invalid User -->
  </suite> <!-- Suite -->
</testng-results>
